### ISSUE TITLE
In the README, Liquid asset identifiers consistent with Blockstream 

### ISSUE THREAD

**Issue by sgornick** [RCasatta/LiquiDEX#1]
I see in the README that there is "LBTC" referring to the Liquid Asset L-BTC.

I would like to see that be consistent with the way that Blockstream refers to it, L-BTC, and not LBTC.

Additionally, I see two references in the README to USDT.  Of course, this is not USDT, but "Liquid USDT".  I've seen references to it (e.g., in [a Tweet by Adam Back](https://twitter.com/adam3us/status/1300586612229902338)) as L-USDT, but Blockstream itself refers to it mostly only as Liquid USDT, though even they [sometimes refer to it on Twitter as L-USD](https://twitter.com/Blockstream/status/1219141403533565952).    So I don't know which of the two, Liquid USDT or L-USDT, is better, but I'ld like to see the usage consistent in that it is differentiated with some prefix and not confused with USDT (which could be Omni USDT, or other blockchains).

For an example of usage, here's an announcement post from Blockstream:
https://blockstream.com/2019/07/29/en-tether-lands-on-the-liquid-network/

But even they are all over the map sometimes, as shown in this support article:
https://help.blockstream.com/hc/en-us/articles/900000642443-Acquire-L-BTC-and-USDt-with-Bitfinex

**Comment by RCasatta** [comment]
Thanks for the heads-up.

I think we should go with what we see in the liquid asset registry https://blockstream.info/liquid/asset which are:
* L-BTC
* USDt

I do agree for tether it's not specified the blockchain they are on, however, is implicit in this context.
